### ISSUE TITLE
Streamlined syntax for typed classes?

### ISSUE THREAD

**Issue by matejcik** [timrid/construct-typing#12]
I'm using `construct-typing` for my typing needs, but I find the design of `construct_typed` a little too unwieldy for my coding style.

For this reason, I created a lightweight project [`construct-classes`](https://github.com/matejcik/construct-classes) that works with a somewhat different syntax:
```python
import construct as c
from construct_classes import Struct, subcon

class BasicStruct(Struct):
    x: int
    y: int
    description: str

    SUBCON = c.Struct(
        "x" / c.Int32ul,
        "y" / c.Int32ul,
        "description" / c.PascalString(c.Int8ul, "utf8"),
    )


data = b"\x01\x00\x00\x00\x02\x00\x00\x00\x05hello"
parsed = BasicStruct.parse(data)
print(parsed)  # BasicStruct(x=1, y=2, description='hello')

new_data = BasicStruct(x=100, y=200, description="world")
print(new_data.build())  # b'\x64\x00\x00\x00\xc8\x00\x00\x00\x05world'
```

I chose to make `SUBCON` a thing separate from field definitions because in my personal experience, pulling out any sort of more complex functionality out of pure Construct and into things like `csfield` proved troublesome.

Because I don't really want to make a new project for new projects' sake, I was wondering if you would be interested in contributions in this direction, and/or wanted to collaborate.

**Comment by timrid** [comment]
I also thought about a similar implementation than yours. But there are a few disadvantages:
1. You have to [repeat](https://en.m.wikipedia.org/wiki/Don%27t_repeat_yourself) all the fields you define. When there are only a few fields like in your example this may be okay, but if there are like 10 or more it gets confusing. 
2. The type checker can not validate if the type you defined in the `dataclass` matches the type you defined in the `construct.Struct`.
3. Your dataclass can not contain fields with the name `build` and `SUBCON`. 

In my implementation I solve all of the disadvantages.

**Comment by matejcik** [comment]
> 1. You have to [repeat](https://en.m.wikipedia.org/wiki/Don%27t_repeat_yourself) all the fields you define. When there are only a few fields like in your example this may be okay, but if there are like 10 or more it gets confusing.

This is a big disadvantage, yes. The offsetting feature is that the "structure" is separate from "data", which is desirable in my usecases: complex structs that have a lot of internal fields used for offset calculations, `Padding`s, `Tell`s, `Terminated` and the like. Also it makes it easier (possible at all?) to parse non-Struct top level objects.

The above suggests that our approaches have fundamentally different usecases so I will keep my project separate and close this issue.
