### ISSUE TITLE
Adapter __init__ takes no arguments

### ISSUE THREAD

**Issue by matejcik** [timrid/construct-typing#13]
here is an example adapter that I am using:
```python
class EnumAdapter(construct.Adapter):
    def __init__(self, subcon: Any, enum: Any) -> None:
        self.enum = enum
        super().__init__(subcon)

    def _encode(self, obj: Any, ctx: Any, path: Any):
        return obj.value

    def _decode(self, obj: Any, ctx: Any, path: Any):
        try:
            return self.enum(obj)
        except ValueError:
            return obj
```

With construct-typing, this does not type-check because `super().__init__()` does not accept positional arguments.
Which is obviously untrue, `Adapter.__init__` delegates to `Subconstruct.__init__` which accepts `subcon` as its single argument.

**Comment by timrid** [comment]
I fixed it on `main`. It will come into the next release.

**Comment by timrid** [comment]
[v0.5.3](https://github.com/timrid/construct-typing/releases/tag/v0.5.3) is released
