### ISSUE TITLE
Upgrade requirement to `construct==2.10.68`?

### ISSUE THREAD

**Issue by demberto** [timrid/construct-typing#14]
https://github.com/timrid/construct-typing/blob/834d244eda588323f28f45f17bc1f276b058088b/setup.py#L24

**Comment by arekbulski** [comment]
Construct .69 will be up any day now.

**Comment by timrid** [comment]
updated requirement to construct==2.10.68 in [v0.5.3](https://github.com/timrid/construct-typing/releases/tag/v0.5.3)
