### ISSUE TITLE
Python 3.11 error

### ISSUE THREAD

**Issue by demberto** [timrid/construct-typing#15]
```console
in <module>
    import construct_typed as ct
construct_typed\__init__.py:21: in <module>
    from .tenum import EnumBase, FlagsEnumBase, TEnum, TFlagsEnum
construct_typed\tenum.py:8: in <module>
    class EnumBase(enum.IntEnum):
construct_typed\tenum.py:25: in EnumBase
    def _create_pseudo_member_(cls, value: int) -> "EnumBase":
\Python311\Lib\enum.py:378: in __setitem__
    raise ValueError(
E   ValueError: _sunder_ names, such as '_create_pseudo_member_', are reserved for future Enum use
```

Precisely this https://github.com/timrid/construct-typing/blob/834d244eda588323f28f45f17bc1f276b058088b/construct_typed/tenum.py#L25-L34

**Comment by timrid** [comment]
Thanks for the bug report. I fixed it on `main`. It will come into the next release.

**Comment by demberto** [comment]
How about not creating a separate method itself? Putting all logic in `_missing_` itself?

**Comment by timrid** [comment]
Good point. I removed `_create_pseudo_member_` completely.

**Comment by demberto** [comment]
@timrid Can you give an estimate on how much time a release will take? I have a project which depends on this library and it seems I cannot publish wheels with a direct git commit dependency

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         Invalid value for requires_dist. Error: Can't have direct dependency: 'construct-typing @
         git+https://github.com/timrid/construct-typing.git@ce871936d9e885c84f2f507c723fc5a7e99c9096'
```

This is the error I got from `twine`. There's no solutions afaik, and google doesn't return much results about this

**Comment by timrid** [comment]
I guess I can make it in a few days. At most a week.

**Comment by timrid** [comment]
[v0.5.3](https://github.com/timrid/construct-typing/releases/tag/v0.5.3) is released

**Comment by demberto** [comment]
Thanks
