### ISSUE TITLE
`EnumBase` members are `int`

### ISSUE THREAD

**Issue by demberto** [timrid/construct-typing#17]
Since mypy 0.991, members of `EnumBase` don't have the type of the class, instead it is `int`.

**Comment by timrid** [comment]
I updated to mypy 0.991 locally, but dont know what you mean. All tests passed. Than I tried the following example:

```python
def test_tenum() -> None:
    class TestEnum(cst.EnumBase):
        one = 1
        two = 2
        four = 4
        eight = 8
    a = TestEnum.one
    reveal_type(a)
```

and mypy==0.931 and mypy==0.991 created the same output:
```
tests\test_typed.py:365: note: Revealed type is "tests.test_typed.TestEnum@359"
```

So I cant see any problem.

**Comment by demberto** [comment]
I dunno what caused this issue, can't repro.
