### ISSUE TITLE
Enum type hints are incorrect for non-byte subcons

### ISSUE THREAD

**Issue by kratsg** [timrid/construct-typing#20]
```
    d = Enum(Bytes(2), one=1, two=2, four=4, eight=8)
```

fails the (mypy) type checker

```
Argument 1 to "Enum" has incompatible type "Bytes[bytes, Union[bytes, int]]"; expected "Construct[int, int]"  [arg-type]
```

**Comment by timrid** [comment]
Your problem is, that the `subcon` of `Enum` has to be an integer type eg. `Int16ul` and not `Bytes(2)`. So this should work:

```python
d = Enum(Int16ul, one=1, two=2, four=4, eight=8)
```

**Comment by kratsg** [comment]
The use case I have is when the values of the Enum are bytes and not integers -- e.g.

```
d = Enum(Int16ul, one=b"11", two=b"22", four=b"44", eight=b"88")
```

Or similar -- which is supported by `Enum`, but I understand why you've limited it.
